#!/bin/sh

#
# Adapted from mdct-00fs:/home/kickstart/picaps/ks.cfg
#

SELF="$(basename $0)"

info() {
    echo "$*"
}


kickstart_clone() {
    #   #platform=x86, AMD64, or Intel EM64T
    #   text
    #   # System authorization information
    #   auth  --useshadow  --enablemd5
    #   # Firewall configuration
    #   firewall --disabled
    #   firstboot --disable
    #   # System keyboard
    #   keyboard us
    #   # System language
    #   lang en_US
    #   # Root password
    #   rootpw --iscrypted $1$q/OLH34/$tSLx.EjE2vkyyhNVMys91/
    #   # SELinux configuration
    #   selinux --disabled

    info "disabling SELinux"
    sed -ci 's/^SELINUX=.*/SELINUX=disabled/' /etc/selinux/config
    setenforce 0

    #   # Install OS instead of upgrade
    #   install
    #   # Use network installation
    #   url --url=http://mdct-00fs/ftp/pub/fedora/7/Fedora/x86_64/os
    #   # Network information
    #   network --bootproto=dhcp --device=eth0 --onboot=on --noipv6 --hostname mdct-??pi
    #   # Reboot after installation
    #   #reboot
    #   # System timezone
    #   timezone  --utc America/Detroit
    #   # X Window System configuration information
    #   xconfig  --defaultdesktop=GNOME --depth=8 --resolution=640x480
    #   # System bootloader configuration
    #   bootloader --location=mbr
    #   # Clear the Master Boot Record
    #   zerombr
    #   # Partition clearing information
    #   clearpart --all --initlabel
    #   # Disk partitioning information
    #   part /boot --fstype="ext3" --ondisk=sda --size=150 --bytes-per-inode=4096 --asprimary --label=BOOT
    #   part swap --fstype="swap" --ondisk=sda --size=16384 --bytes-per-inode=4096 --asprimary
    #   part / --fstype="ext3" --grow --ondisk=sda --size=1 --bytes-per-inode=4096 --asprimary --label=ROOT
    #   part /storage --fstype="ext3" --grow --ondisk=sdb --size=1 --bytes-per-inode=4096 --asprimary --label=STORAGE

    info "making /storage"
    mkdir -p /storage

    #   %post --interpreter=/bin/bash
    #   chkconfig kudzu off
    #   chkconfig yum-updatesd off
    #   chkconfig bluetooth off
    #   chkconfig avahi-daemon off
    #   chkconfig firstboot off
    #   chkconfig ip6tables off
    #   chkconfig iptables off
    #   chkconfig sendmail off
    #   chkconfig syslog on

    #   # NTP Setup
    #   ncftpget 10.1.192.105 /etc/ /pub/kickstart/picaps/ntp.conf
    #   chkconfig ntpd on
    #   /usr/sbin/ntpdate 10.1.0.97
    #   /usr/sbin/hwclock -w --utc --systohc

    #   # YUM Setup / Update
    #   mv /etc/yum.repos.d /etc/yum.repos.d-orig
    #   ncftpget -R 10.1.192.105 /etc/ /pub/kickstart/picaps/yum.repos.d
    #   /usr/bin/yum -y update

    #   # Intelligent Platform Management Interface (IPMI) tools setup
    #   /usr/bin/yum -y install OpenIPMI-tools
    #   cat >> /etc/rc.local <<EOF
    #   # Force load of IPMI modules so that impitool is always ready to go
    #   /sbin/modprobe ipmi_msghandler
    #   /sbin/modprobe ipmi_devintf
    #   /sbin/modprobe ipmi_si
    #   EOF

    #   # Hummingbird Gateway setup
    #   ncftpget -R 10.1.192.105 /home/ /pub/kickstart/picaps/hbgw

    # Java Setup
    # The JDK release and JAVA_HOME differ here from kickstart, but match
    # current production standards.  We set root's JAVA_HOME home to latest
    # rather than using $picaps_jdk because root's tools probably should just
    # use the latest whereas applications (e.g., PICAPS) should probably be
    # explicit for change control purposes.
    if ! rpm -q jdk &> /dev/null
    then
        info "installing JDK"
        rpm -iv <%= jdk_rpm_source %>
        echo -e "JAVA_HOME=/usr/java/latest/\nexport JAVA_HOME" >> /root/.bash_profile
    else
        info "JDK already installed"
    fi

    # jmx password
    info "installing JMX password"
    echo -e "root\tspacip" > <%= picaps_jdk %>/jre/lib/management/jmxremote.password
    chmod 600 <%= picaps_jdk %>/jre/lib/management/jmxremote.password

    # /dist setup
    info "installing PICAPS cvs checkout"
    mkdir -p /dist
    cd /dist
    cvs -d :pserver:anonymous@10.1.192.105:/home/cvsroot co picaps/bin
    cvs -d :pserver:anonymous@10.1.192.105:/home/cvsroot co picaps/config
    cvs -d :pserver:anonymous@10.1.192.105:/home/cvsroot co picaps/static
    cvs -d :pserver:anonymous@10.1.192.105:/home/cvsroot co picaps/resource
    mv /dist/picaps/* /dist
    rm -rf /dist/picaps
    chmod +x /dist/resource/init.d/picaps
    ln -s /dist/resource/init.d/picaps /etc/init.d/picaps
    ln -s /dist/resource/init.d/sysconfig /etc/sysconfig/picaps

    # MySQL Setup
    info "configuring MySQL"
    service mysqld stop 2> /dev/null
    mkdir -p /storage/mysql
    echo -e "/storage/mysql\t\t/var/lib/mysql\t\text4\tbind\t0 0" >> /etc/fstab
    mount /storage/mysql
    mv /etc/my.cnf /etc/my.cnf-orig
    ncftpget 10.1.192.105 /etc/ /pub/kickstart/picaps/my.cnf
    service mysqld start
    mysqladmin create picap
    chkconfig mysqld on
    ncftpget 10.1.192.105 /root/ /pub/kickstart/picaps/grantpicaps.sql
    mysql < /root/grantpicaps.sql
    rm -rf /root/grantpicaps.sql

    # Web Setup
    info "configuring Apache"
    ncftpget 10.1.192.105 /var/www/html/ /pub/kickstart/picaps/www/html/*
    ncftpget 10.1.192.105 /var/www/cgi-bin/ /pub/kickstart/picaps/www/cgi-bin/*
    chmod +x /var/www/cgi-bin/checkWeb.cgi
    # Disable Apache's mod_ssl so that port 443 is free for PICAPS
    sed --in-place 's/^Listen 443/\#&/' /etc/httpd/conf.d/ssl.conf

    #   # rsync
    #   ncftpget 10.1.192.105 /etc/ /pub/kickstart/picaps/rsyncd.conf
    #   ncftpget 10.1.192.105 /etc/xinetd.d/ /pub/kickstart/picaps/rsync
    #   chkconfig xinetd on
    #   chkconfig rsync on

    # Printer Setup
    info "configuring cups"
    service cups start

    # 00 - Corporate / MDC
    /usr/sbin/lpadmin -p LP00051 -E -v socket://10.1.0.147
    /usr/sbin/lpadmin -p LP00052 -E -v socket://10.1.0.164
    /usr/sbin/lpadmin -p LP00053 -E -v socket://10.1.0.166
    /usr/sbin/lpadmin -p LP00054 -E -v socket://10.1.0.169
    /usr/sbin/lpadmin -p LP00055 -E -v socket://10.1.80.7
    /usr/sbin/lpadmin -p LP00056 -E -v socket://10.1.250.162:9900

    # 01 - Mason
    /usr/sbin/lpadmin -p LP01011 -E -v socket://10.1.193.1:9900
    /usr/sbin/lpadmin -p LP01012 -E -v socket://10.1.193.2:9900
    /usr/sbin/lpadmin -p LP01013 -E -v socket://10.1.193.3:9900

    # 02 - Leola
    /usr/sbin/lpadmin -p LP02011 -E -v socket://10.2.193.2:9900
    /usr/sbin/lpadmin -p LP02012 -E -v socket://10.2.193.3:9900
    /usr/sbin/lpadmin -p LP02013 -E -v socket://10.2.193.16:9900
    /usr/sbin/lpadmin -p LP02014 -E -v socket://10.2.193.4:9900
    /usr/sbin/lpadmin -p LP02015 -E -v socket://10.2.193.8:9900
    /usr/sbin/lpadmin -p LP02016 -E -v socket://10.2.193.9:9900
    /usr/sbin/lpadmin -p LP02017 -E -v socket://10.2.0.53:9900
    /usr/sbin/lpadmin -p LP02018 -E -v socket://10.2.193.14:9900
    /usr/sbin/lpadmin -p LP02019 -E -v socket://10.2.193.15:9900
    /usr/sbin/lpadmin -p LP0201A -E -v socket://10.2.193.18:9900
    /usr/sbin/lpadmin -p LP0201B -E -v socket://10.2.193.19:9900
    /usr/sbin/lpadmin -p LP02041 -E -v socket://10.2.193.11:9900
    /usr/sbin/lpadmin -p LP02051 -E -v socket://10.2.193.5:9900
    /usr/sbin/lpadmin -p LP02061 -E -v socket://10.2.193.10:9900
    /usr/sbin/lpadmin -p LP02062 -E -v socket://10.2.193.6:9900
    /usr/sbin/lpadmin -p LP02063 -E -v socket://10.2.193.7:9900
    /usr/sbin/lpadmin -p LP02064 -E -v socket://10.2.193.13:9900
    /usr/sbin/lpadmin -p LP02081 -E -v socket://10.2.0.52:9900
    /usr/sbin/lpadmin -p LP02121 -E -v socket://10.2.193.1:9900
    /usr/sbin/lpadmin -p LP02131 -E -v socket://10.2.193.12:9900

    # 03 - Lithonia
    /usr/sbin/lpadmin -p LP03011 -E -v socket://10.3.193.1:9900
    /usr/sbin/lpadmin -p LP03012 -E -v socket://10.3.193.2:9900
    /usr/sbin/lpadmin -p LP03013 -E -v socket://10.3.193.3:9900

    # 04 - Aurora
    /usr/sbin/lpadmin -p LP04011 -E -v socket://10.4.193.1:9900
    /usr/sbin/lpadmin -p LP04012 -E -v socket://10.4.193.2:9900
    /usr/sbin/lpadmin -p LP04013 -E -v socket://10.4.193.3:9900
    /usr/sbin/lpadmin -p LP04014 -E -v socket://10.4.193.4:9900
    /usr/sbin/lpadmin -p LP04015 -E -v socket://10.4.193.5:9900
    /usr/sbin/lpadmin -p LP04016 -E -v socket://10.4.193.6:9900
    /usr/sbin/lpadmin -p LP04017 -E -v socket://10.4.193.7:9900
    /usr/sbin/lpadmin -p LP0401BPRN -E -v socket://10.4.193.30:9900

    # 05 - Corona
    /usr/sbin/lpadmin -p LP05011 -E -v socket://10.5.193.1:9900
    /usr/sbin/lpadmin -p LP05012 -E -v socket://10.5.193.2:9900
    /usr/sbin/lpadmin -p LP05013 -E -v socket://10.5.193.3:9900
    /usr/sbin/lpadmin -p LP05031 -E -v socket://10.5.193.4:9900
    /usr/sbin/lpadmin -p LP05032 -E -v socket://10.5.193.5:9900
    /usr/sbin/lpadmin -p LP0501BPRN -E -v socket://10.5.193.30:9900

    # 10 - Waxahachie
    /usr/sbin/lpadmin -p LP10011 -E -v socket://10.10.193.1:9900
    /usr/sbin/lpadmin -p LP10012 -E -v socket://10.10.193.2:9900
    /usr/sbin/lpadmin -p LP10013 -E -v socket://10.10.193.3:9900
    /usr/sbin/lpadmin -p LP10014 -E -v socket://10.10.193.4:9900
    /usr/sbin/lpadmin -p LP10015 -E -v socket://10.10.193.5:9900
    /usr/sbin/lpadmin -p LP10016 -E -v socket://10.10.193.6:9900
    /usr/sbin/lpadmin -p LP10017 -E -v socket://10.10.193.7:9900
    /usr/sbin/lpadmin -p LP10018 -E -v socket://10.10.193.8:9900
    /usr/sbin/lpadmin -p LP10019 -E -v socket://10.10.193.9:9900
    /usr/sbin/lpadmin -p LP1000A -E -v socket://10.10.193.10:9900
    /usr/sbin/lpadmin -p LP1001BPRN -E -v socket://10.10.193.30:9900

    # 11 - HorseCave
    /usr/sbin/lpadmin -p LP11011 -E -v socket://10.11.193.1:9900
    /usr/sbin/lpadmin -p LP11012 -E -v socket://10.11.193.3:9900
    /usr/sbin/lpadmin -p LP11013 -E -v socket://10.11.193.4:9900
    /usr/sbin/lpadmin -p LP11031 -E -v socket://10.11.193.2:9900
    /usr/sbin/lpadmin -p LP11014 -E -v socket://10.11.193.5:9900

    # 15 - Quitman
    /usr/sbin/lpadmin -p LP15011 -E -v socket://10.15.193.1:9900
    /usr/sbin/lpadmin -p LP15012 -E -v socket://10.15.193.2:9900

    # 19 - Plant City, FL
    /usr/sbin/lpadmin -p LP19011 -E -v socket://10.19.193.1:9900
    /usr/sbin/lpadmin -p LP19012 -E -v socket://10.19.193.2:9900
    /usr/sbin/lpadmin -p LP19013 -E -v socket://10.19.193.3:9900
    /usr/sbin/lpadmin -p LP19014 -E -v socket://10.19.193.4:9900
    /usr/sbin/lpadmin -p LP1901BPRN -E -v socket://10.19.193.30:9900

    # 25 - Tumwater
    /usr/sbin/lpadmin -p LP25011 -E -v socket://10.25.193.3:9900
    /usr/sbin/lpadmin -p LP25012 -E -v socket://10.25.193.2:9900
    /usr/sbin/lpadmin -p LP2501BPRN -E -v socket://10.25.193.30:9900

    # 39 - Randleman
    /usr/sbin/lpadmin -p LP39011 -E -v socket://10.39.193.1:9900

    # 52 - Lancaster
    /usr/sbin/lpadmin -p LP52011 -E -v socket://10.52.193.1:9900

    # 55 - Lodi
    /usr/sbin/lpadmin -p LP55011 -E -v socket://10.55.193.1:9900
    /usr/sbin/lpadmin -p LP55012 -E -v socket://10.55.193.2:9900
    /usr/sbin/lpadmin -p LP55013 -E -v socket://10.55.193.3:9900
    /usr/sbin/lpadmin -p LP5501BPRN -E -v socket://10.55.193.30:9900

    # 72 - Tijuana
    /usr/sbin/lpadmin -p LP72011 -E -v socket://10.72.193.1:9900
    /usr/sbin/lpadmin -p LP72012 -E -v socket://10.72.193.2:9900
    /usr/sbin/lpadmin -p LP72013 -E -v socket://10.72.193.3:9900
    /usr/sbin/lpadmin -p LP72014 -E -v socket://10.72.193.4:9900
    /usr/sbin/lpadmin -p LP72015 -E -v socket://10.72.193.5:9900
    /usr/sbin/lpadmin -p LP7201BPRN -E -v socket://10.72.193.30:9900

    # 75 - England
    /usr/sbin/lpadmin -p LP75011 -E -v socket://10.75.193.1:9900
    /usr/sbin/lpadmin -p LP75012 -E -v socket://10.75.193.2:9900
    /usr/sbin/lpadmin -p LP75013 -E -v socket://10.75.193.3:9900
    /usr/sbin/lpadmin -p LP75014 -E -v socket://10.75.193.4:9900
    /usr/sbin/lpadmin -p LP75015 -E -v socket://10.75.193.5:9900
    /usr/sbin/lpadmin -p LP7501BPRN -E -v socket://10.75.193.30:9900

    # 76 - Australia
    /usr/sbin/lpadmin -p LP76011 -E -v socket://10.76.193.1:9900
    /usr/sbin/lpadmin -p LP76012 -E -v socket://10.76.193.2:9900

    # 77 - Canada
    /usr/sbin/lpadmin -p LP77011 -E -v socket://10.77.193.2:9900
    /usr/sbin/lpadmin -p LP7701BPRN -E -v socket://10.77.193.30:9900

    # 78 - Mexico
    /usr/sbin/lpadmin -p LP78011 -E -v socket://10.78.193.1:9900
    /usr/sbin/lpadmin -p LP78012 -E -v socket://10.78.193.2:9900

    # Install verification script
    info "installing PICAPS verification script"
    ncftpget 10.1.192.105 /root/ /pub/kickstart/picaps/verify.py
    chmod +x /root/verify.py

    #   # Update locate database
    #   /usr/bin/updatedb

    #   %packages
    #   @mysql
    #   @admin-tools
    #   @editors
    #   @system-tools
    #   @text-internet
    #   @gnome-desktop
    #   @base
    #   @ftp-server
    #   @network-server
    #   @hardware-support
    #   @base-x
    #   @web-server
    #   @smb-server
    #   @printing
    #   @server-cfg
    #   php-mysql
    #   vim-X11
    #   lynx
    #   ncftp
    #   vnc-server
    #   acpi
    #   hddtemp
    #   acpitool
    #   firmware-addon-dell
    #   -iwlwifi-firmware
    #   cvs
    #   xinetd

    #   #%end

    info "$SELF: finished"
}

kickstart_clone &> /root/picaps-install-and-setup.log
