forge "http://forge.puppetlabs.com"

# Modules from the Puppet Forge
# Note the versions are all set to :latest but after you've 
# installed you should change them to the exact version you want
mod "puppetlabs-apt",         :latest
mod "puppetlabs-concat",      :latest
mod "puppetlabs-mysql",       :latest
mod "puppetlabs-postgresql",  :latest
mod "puppetlabs-sqlite",      :latest
mod "puppetlabs-stdlib",      :latest
mod "puppetlabs-vcsrepo",     :latest
mod "ringingliberty-chrony",  :latest
mod "mosen-cups",             :latest
mod "yo61-logrotate",         :latest

#An example of using a specific forge module version instead of latest
#Notice the addition of single quotes
#mod "puppetlabs/inifile", '1.3.0'

# Modules from Github using various references
# Further examples: https://github.com/puppetlabs/r10k/blob/master/doc/puppetfile.mkd#examples
# update the tag to the most current release when implementing

#mod 'gitlab',
#  :git => 'https://github.com/vshn/puppet-gitlab',
#  :ref => '00397b86dfb3487d9df768cbd3698d362132b5bf'
#
#mod 'r10k',
#  :git => 'https://github.com/acidprime/r10k',
#  :tag => 'v3.1.1'

